
spring.application.name=Expense_Tracker

server.port=${PORT:8080}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET}
jwt.expiration=36000000











#
#spring.application.name=Expense_Tracker
#
#server.port = 8004
#spring.datasource.url=jdbc:postgresql://localhost:5432/ExpenseTracker
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#spring.datasource.driver-class-name=org.postgresql.Driver
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=false
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.format_sql=true
#
#
#
#jwt.secret=YourSuperSecretKeyThatIsAtLeast32CharactersLong123456
#jwt.expiration=36000000

# Render PostgreSQL specific HikariCP connection pool settings
# Render drops idle connections after 5 minutes (300,000ms), which causes the app to hang.
# Setting max-lifetime and idle-timeout below 5 minutes prevents HikariCP from using dropped connections.

spring.datasource.hikari.max-lifetime=270000
spring.datasource.hikari.idle-timeout=120000
spring.datasource.hikari.keepalive-time=30000
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=10
